/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculations;

import java.awt.event.KeyEvent;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
/**
 *
 * @author kasuni
 */
public class interface_cal extends javax.swing.JFrame {

    double n1;
    double n2;
    double result; 
    String opr;
    private Object math;
    double memorydisplay;
    boolean isEquelClicked;
    boolean isBtnClicked=false;
    boolean isNumBtnClicked;
    double temp;
    double memory;
    
    
    
    public interface_cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        tfDisplay = new javax.swing.JTextField();
        jbMOD = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jbMUL = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jbADD = new javax.swing.JButton();
        jbpoint = new javax.swing.JButton();
        jbPLUSMINUS = new javax.swing.JButton();
        jb0 = new javax.swing.JButton();
        jbDIV = new javax.swing.JButton();
        jbEQL = new javax.swing.JButton();
        jbSUB = new javax.swing.JButton();
        jbPOW = new javax.swing.JButton();
        jbBACKS = new javax.swing.JButton();
        jbTAN = new javax.swing.JButton();
        jbCOS = new javax.swing.JButton();
        jbSIN = new javax.swing.JButton();
        jbLOG = new javax.swing.JButton();
        jbSQR = new javax.swing.JButton();
        jbCOSEC = new javax.swing.JButton();
        jbCLEAR = new javax.swing.JButton();
        jbCOT = new javax.swing.JButton();
        jbSEC = new javax.swing.JButton();
        jbPI = new javax.swing.JButton();
        jbROUND = new javax.swing.JButton();
        jbPOW2 = new javax.swing.JButton();
        jbPOW3 = new javax.swing.JButton();
        jbCBRT = new javax.swing.JButton();
        jbBINARY = new javax.swing.JButton();
        jbHEXADECIMAL = new javax.swing.JButton();
        jbOCT = new javax.swing.JButton();
        jbCOSH = new javax.swing.JButton();
        jbSINH = new javax.swing.JButton();
        jbTANH = new javax.swing.JButton();
        jbMS = new javax.swing.JButton();
        jbMR = new javax.swing.JButton();
        jbMC = new javax.swing.JButton();
        jbDEGREE = new javax.swing.JButton();
        jbRAD = new javax.swing.JButton();
        jbINV = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        tfDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDisplayActionPerformed(evt);
            }
        });
        tfDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDisplayKeyTyped(evt);
            }
        });

        jbMOD.setText("%");
        jbMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMODActionPerformed(evt);
            }
        });

        jb4.setText("4");
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });

        jb5.setText("5");
        jb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb5ActionPerformed(evt);
            }
        });

        jb7.setText("7");
        jb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb7ActionPerformed(evt);
            }
        });

        jb8.setText("8");
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });

        jb9.setText("9");
        jb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb9ActionPerformed(evt);
            }
        });

        jb6.setText("6");
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });

        jb2.setText("2");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jbMUL.setText("*");
        jbMUL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMULActionPerformed(evt);
            }
        });

        jb3.setText("3");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jb1.setText("1");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jbADD.setText("+");
        jbADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbADDActionPerformed(evt);
            }
        });

        jbpoint.setText(".");
        jbpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpointActionPerformed(evt);
            }
        });

        jbPLUSMINUS.setText("+/-");
        jbPLUSMINUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPLUSMINUSActionPerformed(evt);
            }
        });

        jb0.setText("0");
        jb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb0ActionPerformed(evt);
            }
        });

        jbDIV.setText("/");
        jbDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDIVActionPerformed(evt);
            }
        });

        jbEQL.setText("=");
        jbEQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEQLActionPerformed(evt);
            }
        });

        jbSUB.setText("-");
        jbSUB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSUBActionPerformed(evt);
            }
        });

        jbPOW.setText("x^y");
        jbPOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPOWActionPerformed(evt);
            }
        });

        jbBACKS.setText("←");
        jbBACKS.setToolTipText("");
        jbBACKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBACKSActionPerformed(evt);
            }
        });

        jbTAN.setText("tan");
        jbTAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTANActionPerformed(evt);
            }
        });

        jbCOS.setText("cos");
        jbCOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCOSActionPerformed(evt);
            }
        });

        jbSIN.setText("sin");
        jbSIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSINActionPerformed(evt);
            }
        });

        jbLOG.setText("log");
        jbLOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLOGActionPerformed(evt);
            }
        });

        jbSQR.setText("√");
        jbSQR.setToolTipText("");
        jbSQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSQRActionPerformed(evt);
            }
        });

        jbCOSEC.setText("cosec");
        jbCOSEC.setToolTipText("");
        jbCOSEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCOSECActionPerformed(evt);
            }
        });

        jbCLEAR.setText("C");
        jbCLEAR.setToolTipText("");
        jbCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCLEARActionPerformed(evt);
            }
        });

        jbCOT.setText("cot");
        jbCOT.setToolTipText("");
        jbCOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCOTActionPerformed(evt);
            }
        });

        jbSEC.setText("sec");
        jbSEC.setToolTipText("");
        jbSEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSECActionPerformed(evt);
            }
        });

        jbPI.setText("pi");
        jbPI.setToolTipText("");
        jbPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPIActionPerformed(evt);
            }
        });

        jbROUND.setText("RND");
        jbROUND.setToolTipText("");
        jbROUND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbROUNDActionPerformed(evt);
            }
        });

        jbPOW2.setText("x^2");
        jbPOW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPOW2ActionPerformed(evt);
            }
        });

        jbPOW3.setText("x^3");
        jbPOW3.setToolTipText("");
        jbPOW3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPOW3ActionPerformed(evt);
            }
        });

        jbCBRT.setText("cbrt");
        jbCBRT.setToolTipText("");
        jbCBRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCBRTActionPerformed(evt);
            }
        });

        jbBINARY.setText("bin");
        jbBINARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBINARYActionPerformed(evt);
            }
        });

        jbHEXADECIMAL.setText("hex");
        jbHEXADECIMAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHEXADECIMALActionPerformed(evt);
            }
        });

        jbOCT.setText("oct");
        jbOCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOCTActionPerformed(evt);
            }
        });

        jbCOSH.setText("cosh");
        jbCOSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCOSHActionPerformed(evt);
            }
        });

        jbSINH.setText("sinh");
        jbSINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSINHActionPerformed(evt);
            }
        });

        jbTANH.setText("tanh");
        jbTANH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTANHActionPerformed(evt);
            }
        });

        jbMS.setText("MS");
        jbMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMSActionPerformed(evt);
            }
        });

        jbMR.setText("MR");
        jbMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMRActionPerformed(evt);
            }
        });

        jbMC.setText("MC");
        jbMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMCActionPerformed(evt);
            }
        });

        jbDEGREE.setText("degree");
        jbDEGREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDEGREEActionPerformed(evt);
            }
        });

        jbRAD.setText("RAD");
        jbRAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRADActionPerformed(evt);
            }
        });

        jbINV.setText("1/x");
        jbINV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbINVActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbADD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSQR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBACKS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbBINARY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbHEXADECIMAL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbOCT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbPOW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPOW2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPOW3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCBRT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMUL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbINV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPLUSMINUS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbEQL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbDEGREE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbRAD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSIN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbCOS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbTAN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSINH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbCOSEC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbSEC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbCOT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbTANH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(tfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tfDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBACKS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBINARY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbHEXADECIMAL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOCT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSUB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPOW, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPOW2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPOW3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbADD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSQR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCBRT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLOG, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMUL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbINV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSIN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCOS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTAN, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPLUSMINUS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSINH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCOSH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbTANH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbDEGREE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCOSEC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbCOT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSEC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbEQL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbRAD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb7ActionPerformed
        if(isEquelClicked==true){
            tfDisplay.setText("");
            isEquelClicked=false;
        }
        String n=tfDisplay.getText() + jb7.getText();
        tfDisplay.setText(n);
        isNumBtnClicked=true;
    }//GEN-LAST:event_jb7ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb8.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
        
    }//GEN-LAST:event_jb8ActionPerformed

    private void jbDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDIVActionPerformed

     if(isNumBtnClicked==true){
            tfDisplay.setText(tfDisplay.getText()+"/");
            isNumBtnClicked = false;
      }
    }//GEN-LAST:event_jbDIVActionPerformed

    private void jbEQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEQLActionPerformed
    
     //   result=Double.parseDouble(String.valueOf(tfDisplay.getText()));
        
        ScriptEngineManager mgr = new ScriptEngineManager();
        String shortName;
        ScriptEngine engine = mgr.getEngineByName("javascript");

        String foo = tfDisplay.getText();

        try {
        tfDisplay.setText(engine.eval(foo).toString());

        } catch (ScriptException e) {
            e.printStackTrace();
        }
        
        /*  String answer;
        isEquelClicked=true;
        n2 = Double.parseDouble(tfDisplay.getText());
        if(opr == "+"){
            
            result=n1+n2;
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;
        }
        else if(opr=="-"){
            result=n1-n2;
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;
            
        }else if(opr=="*"){
            result=n1*n2;
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;

        }else if(opr=="/"){
            result=n1/n2;
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;

        }else if(opr=="%"){
            result=n1%n2;
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;

        }else if(opr=="x^y"){
            result=Math.pow(n1, n2);
            tfDisplay.setText(String.valueOf(result));
            isBtnClicked=false;
            n1=0;
        }*/
               
        
    }//GEN-LAST:event_jbEQLActionPerformed

    private void jbSUBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSUBActionPerformed
     
     if(isNumBtnClicked==true){
        tfDisplay.setText(tfDisplay.getText()+"-");
        isNumBtnClicked=false;
     }
      
    }//GEN-LAST:event_jbSUBActionPerformed

    private void jbPOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPOWActionPerformed
        if (isBtnClicked == true) {
            n2 = Double.parseDouble(tfDisplay.getText());
            tfDisplay.setText("");
            n1 =Math.pow(n1, n2);
            opr = ("x^y");
        } else {
            n1 = Double.parseDouble(tfDisplay.getText());
            tfDisplay.setText("");
            opr = ("x^y");
            isBtnClicked = true;
        }
    }//GEN-LAST:event_jbPOWActionPerformed

    private void jbBACKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBACKSActionPerformed
        String backspce=null;
        if(tfDisplay.getText().length()>0){
            StringBuilder strb= new StringBuilder(tfDisplay.getText());
            strb.deleteCharAt(tfDisplay.getText().length()-1);
            backspce=strb.toString();
            tfDisplay.setText(backspce);
            
        }
        
    }//GEN-LAST:event_jbBACKSActionPerformed

    private void jbTANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTANActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.tan(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbTANActionPerformed

    private void jbCOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCOSActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.cos(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbCOSActionPerformed

    private void jbSINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSINActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.sin(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbSINActionPerformed

    private void jbLOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLOGActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.log(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbLOGActionPerformed

    private void jb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb5ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb5.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb5ActionPerformed

    private void tfDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDisplayActionPerformed

    
    private void jbADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbADDActionPerformed
     
      if(isNumBtnClicked==true){
        tfDisplay.setText(tfDisplay.getText() + "+");
          isNumBtnClicked = false;
      }     
       
        
       
    }//GEN-LAST:event_jbADDActionPerformed

    private void jbSQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSQRActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.sqrt(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbSQRActionPerformed

    private void jb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb9ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb9.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb9ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb4.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb6.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb1.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb2.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n=tfDisplay.getText() + jb3.getText();
        tfDisplay.setText(n);
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb3ActionPerformed

    private void jbCOSECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCOSECActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.toRadians(num);
        num = Math.sin(num);
        num=1/num;
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbCOSECActionPerformed

    private void jbCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCLEARActionPerformed
      tfDisplay.setText("");
    }//GEN-LAST:event_jbCLEARActionPerformed

    private void jbCOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCOTActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.toRadians(num);
        num = Math.tan(num);
        num=1/num;
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbCOTActionPerformed

    private void jb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb0ActionPerformed
        if (isEquelClicked == true) {
            tfDisplay.setText("");
            isEquelClicked = false;
        }
        String n = tfDisplay.getText() + jb0.getText();
        tfDisplay.setText(n); 
        isNumBtnClicked = true;
    }//GEN-LAST:event_jb0ActionPerformed

    private void jbpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpointActionPerformed
       if(!tfDisplay.getText().contains(".")){
           tfDisplay.setText(tfDisplay.getText()+jbpoint.getText());
       }
    }//GEN-LAST:event_jbpointActionPerformed

    private void jbPLUSMINUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPLUSMINUSActionPerformed
        double num=Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=(-1)*num;
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbPLUSMINUSActionPerformed

    private void jbMULActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMULActionPerformed
  
     if(isNumBtnClicked==true){
        tfDisplay.setText(tfDisplay.getText()+"*");
         isNumBtnClicked = false;
     }
    }//GEN-LAST:event_jbMULActionPerformed

    private void jbSECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSECActionPerformed
         double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.cos(num);
        num=1/num;
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbSECActionPerformed

    private void jbPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPIActionPerformed
        double num= 3.1415926535897932384626433832795;
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbPIActionPerformed

    private void jbROUNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbROUNDActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.round(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbROUNDActionPerformed

    private void jbPOW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPOW2ActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.pow(num, 2);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbPOW2ActionPerformed

    private void jbPOW3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPOW3ActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.pow(num, 3);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbPOW3ActionPerformed

    private void jbCBRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCBRTActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.cbrt(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbCBRTActionPerformed

    private void jbBINARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBINARYActionPerformed
        int num = Integer.parseInt(tfDisplay.getText());
        tfDisplay.setText(Integer.toString(num,2));
    }//GEN-LAST:event_jbBINARYActionPerformed

    private void jbHEXADECIMALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHEXADECIMALActionPerformed
        int num = Integer.parseInt(tfDisplay.getText());
        tfDisplay.setText(Integer.toString(num, 16));
    }//GEN-LAST:event_jbHEXADECIMALActionPerformed

    private void jbOCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOCTActionPerformed
        int num = Integer.parseInt(tfDisplay.getText());
        tfDisplay.setText(Integer.toString(num, 8));
    }//GEN-LAST:event_jbOCTActionPerformed

    private void tfDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDisplayKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)|| (ch==KeyEvent.VK_BACK_SPACE) || (ch== KeyEvent.VK_DELETE))){
            evt.consume();
    
            
        
        }
    }//GEN-LAST:event_tfDisplayKeyTyped

    private void jbMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMODActionPerformed
      if(isNumBtnClicked==true){
       tfDisplay.setText(tfDisplay.getText()+"%");
         isNumBtnClicked = false;
     }
    }//GEN-LAST:event_jbMODActionPerformed

    private void jbTANHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTANHActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.tanh(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbTANHActionPerformed

    private void jbCOSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCOSHActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num=Math.toRadians(num);
        num = Math.cosh(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbCOSHActionPerformed

    private void jbSINHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSINHActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num =Math.toRadians(num);
        num=Math.sinh(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbSINHActionPerformed

    private void jbMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMSActionPerformed
      //  tfDisplay.setText(String.valueOf(tfDisplay.getText()));
        memory=Double.parseDouble(String.valueOf(tfDisplay.getText()));
    }//GEN-LAST:event_jbMSActionPerformed

    private void jbRADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRADActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.toRadians(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbRADActionPerformed

    private void jbDEGREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDEGREEActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = Math.toDegrees(num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbDEGREEActionPerformed

    private void jbINVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbINVActionPerformed
        double num = Double.parseDouble(String.valueOf(tfDisplay.getText()));
        num = (1 / num);
        tfDisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbINVActionPerformed

    private void jbMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMRActionPerformed
       //tfDisplay.setText(String.valueOf(tfDisplay.getText()));
       n1=memory;
       isBtnClicked=true;
    }//GEN-LAST:event_jbMRActionPerformed

    private void jbMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMCActionPerformed
        memory=0;
    }//GEN-LAST:event_jbMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface_cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jb0;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private javax.swing.JButton jbADD;
    private javax.swing.JButton jbBACKS;
    private javax.swing.JButton jbBINARY;
    private javax.swing.JButton jbCBRT;
    private javax.swing.JButton jbCLEAR;
    private javax.swing.JButton jbCOS;
    private javax.swing.JButton jbCOSEC;
    private javax.swing.JButton jbCOSH;
    private javax.swing.JButton jbCOT;
    private javax.swing.JButton jbDEGREE;
    private javax.swing.JButton jbDIV;
    private javax.swing.JButton jbEQL;
    private javax.swing.JButton jbHEXADECIMAL;
    private javax.swing.JButton jbINV;
    private javax.swing.JButton jbLOG;
    private javax.swing.JButton jbMC;
    private javax.swing.JButton jbMOD;
    private javax.swing.JButton jbMR;
    private javax.swing.JButton jbMS;
    private javax.swing.JButton jbMUL;
    private javax.swing.JButton jbOCT;
    private javax.swing.JButton jbPI;
    private javax.swing.JButton jbPLUSMINUS;
    private javax.swing.JButton jbPOW;
    private javax.swing.JButton jbPOW2;
    private javax.swing.JButton jbPOW3;
    private javax.swing.JButton jbRAD;
    private javax.swing.JButton jbROUND;
    private javax.swing.JButton jbSEC;
    private javax.swing.JButton jbSIN;
    private javax.swing.JButton jbSINH;
    private javax.swing.JButton jbSQR;
    private javax.swing.JButton jbSUB;
    private javax.swing.JButton jbTAN;
    private javax.swing.JButton jbTANH;
    private javax.swing.JButton jbpoint;
    private javax.swing.JTextField tfDisplay;
    // End of variables declaration//GEN-END:variables

    private String tfDisplay(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
